const state={library:null,folder:"",page:1,expanded:new Set(),asset:null,img:null,recipe:blankRecipe(),mode:"operator",tool:"hand",zoom:1,panX:0,panY:0,drag:null};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function blankRecipe(){return {crop:{x:0,y:0,width:1,height:1},adjustments:{brightness:0,contrast:0,saturation:0,temperature:0},filter:"none"};}
async function api(url,opts={}){opts.headers={...(opts.headers||{}),'X-App-Mode':state.mode};const r=await fetch(url,opts);const d=await r.json();if(!r.ok)throw Error(d.error||r.statusText);return d;}
async function load(){let p=new URLSearchParams({folder:state.folder,page:state.page,q:$('#search').value});state.library=await api('/api/library?'+p);renderGrid();$('#status').textContent=`${state.library.total} images · ${state.library.root}`;}
async function loadFolders(){let data=await api('/api/folders');state.folders=data.folders;state.root=data.root;renderFolders()}
function folderTree(){let root={children:{}};for(const path of state.folders){let node=root;for(const part of path.split('/')){if(!part)continue;node.children[part]??={children:{},path:node.path?`${node.path}/${part}`:part};node=node.children[part]}}return root}
function treeHtml(node){return Object.values(node.children).sort((a,b)=>a.path.localeCompare(b.path)).map(n=>`<details ${state.expanded.has(n.path)?'open':''}><summary class="tree-folder ${n.path===state.folder?'active':''}" data-folder="${esc(n.path)}">${esc(n.path.split('/').at(-1))}</summary>${treeHtml(n)}</details>`).join('')}
function renderFolders(){let tree=folderTree();$('#folders').innerHTML=treeHtml(tree);$$('[data-folder]').forEach(b=>b.onclick=()=>{let details=b.parentElement;details.open=!details.open;if(details.open)state.expanded.add(b.dataset.folder);else state.expanded.delete(b.dataset.folder);state.folder=b.dataset.folder;state.page=1;load()})}
function renderGrid(){let items=state.library.assets;$('#folderTitle').textContent=state.folder||'Library';$('#resultCount').textContent=state.library.total?`${(state.library.page-1)*5+1}–${Math.min(state.library.page*5,state.library.total)} of ${state.library.total}`:'No images';$('#grid').innerHTML=items.length?items.map(a=>`<article class="card" data-id="${a.id}"><img class="thumb" loading="lazy" src="${a.url}"><div class="caption">${esc(a.name)}<small>${esc(a.folder||'root')}</small></div></article>`).join(''):'<div class="empty">No images found.</div>';$$('.card').forEach(c=>c.onclick=()=>openEditor(c.dataset.id));let pages=state.library.pages;$('#pagination').innerHTML=pages>1?`<button data-page="${state.library.page-1}" ${state.library.page===1?'disabled':''}>Previous</button><span>Page ${state.library.page} / ${pages}</span><button data-page="${state.library.page+1}" ${state.library.page===pages?'disabled':''}>Next</button>`:'';$$('[data-page]').forEach(b=>b.onclick=()=>{state.page=+b.dataset.page;load()})}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c))}
function get(path){return path.split('.').reduce((o,k)=>o[k],state.recipe)} function set(path,v){let p=path.split('.');let o=state.recipe;for(let i=0;i<p.length-1;i++)o=o[p[i]];o[p.at(-1)]=+v}
function syncControls(){ $$('[data-key]').forEach(i=>{i.value=get(i.dataset.key);i.nextElementSibling.textContent=Number(i.value).toFixed(2)});$('#filter').value=state.recipe.filter; }
function draw(fullResolution=false){if(!state.img)return;let r=state.recipe,c=state.img,scale=fullResolution?1:Math.min(1,900/c.naturalWidth);let sx=r.crop.x*c.naturalWidth,sy=r.crop.y*c.naturalHeight,sw=r.crop.width*c.naturalWidth,sh=r.crop.height*c.naturalHeight;sw=Math.min(sw,c.naturalWidth-sx);sh=Math.min(sh,c.naturalHeight-sy);let canvas=$('#canvas');canvas.width=Math.max(1,sw*scale);canvas.height=Math.max(1,sh*scale);let x=canvas.getContext('2d');let b=100+100*r.adjustments.brightness,con=1+r.adjustments.contrast;x.filter=`brightness(${b}%) contrast(${con}) saturate(${1+r.adjustments.saturation}) ${r.filter==='mono'?'grayscale(1)':''}`;x.drawImage(c,sx,sy,sw,sh,0,0,canvas.width,canvas.height);if(r.filter==='warm'){x.fillStyle='rgba(255,150,50,.12)';x.fillRect(0,0,canvas.width,canvas.height)}if(r.adjustments.temperature){let t=r.adjustments.temperature,alpha=Math.abs(t)*.2;x.fillStyle=t>0?`rgba(255,145,55,${alpha})`:`rgba(65,140,255,${alpha})`;x.fillRect(0,0,canvas.width,canvas.height)}canvas.style.transform=`translate(${state.panX}px,${state.panY}px) scale(${state.zoom})`;$('#zoomLabel').textContent=`${Math.round(state.zoom*100)}%`}
function autoWhiteBalance(){if(!state.img)return;let r=state.recipe,c=state.img,probe=document.createElement('canvas'),ctx=probe.getContext('2d'),sx=r.crop.x*c.naturalWidth,sy=r.crop.y*c.naturalHeight,sw=r.crop.width*c.naturalWidth,sh=r.crop.height*c.naturalHeight;probe.width=64;probe.height=64;ctx.drawImage(c,sx,sy,sw,sh,0,0,64,64);let pixels=ctx.getImageData(0,0,64,64).data,red=0,blue=0,count=pixels.length/4;for(let i=0;i<pixels.length;i+=4){red+=pixels[i];blue+=pixels[i+2]}r.adjustments.temperature=Math.max(-1,Math.min(1,(blue-red)/count/100));syncControls();draw()}
function renderVariants(){let variants=state.asset.recipes||[];$('#variants').innerHTML=variants.length?`<div>Saved variants</div>${variants.map((v,i)=>`<div class="variant-row"><button class="variant" data-variant="${v.id}">${i+1}</button><button class="variant-delete" data-delete-variant="${v.id}" title="Delete variant" aria-label="Delete variant ${i+1}">×</button></div>`).join('')}`:'No saved variants yet';$$('.variant').forEach(b=>b.onclick=()=>{let v=variants.find(x=>x.id===b.dataset.variant);state.recipe={crop:{...v.crop},adjustments:{...v.adjustments,temperature:v.adjustments.temperature||0},filter:v.filter||'none'};syncControls();draw()});$$('.variant-delete').forEach(b=>b.onclick=async()=>{if(!confirm(`Delete variant ${variants.findIndex(v=>v.id===b.dataset.deleteVariant)+1}?`))return;try{await api(`/api/recipes/${state.asset.id}/${b.dataset.deleteVariant}`,{method:'DELETE'});state.asset.recipes=state.asset.recipes.filter(v=>v.id!==b.dataset.deleteVariant);renderVariants()}catch(e){alert(e.message)}})}
async function openEditor(id){state.asset=state.library.assets.find(a=>a.id===id);state.recipe=blankRecipe();state.zoom=1;state.panX=0;state.panY=0;state.img=new Image();state.img.onload=()=>{syncControls();draw()};state.img.src=state.asset.url;$('#editorTitle').textContent=state.asset.name;$('#editor').classList.remove('hidden');renderVariants();}
$$('[data-key]').forEach(i=>i.oninput=()=>{set(i.dataset.key,i.value);i.nextElementSibling.textContent=Number(i.value).toFixed(2);draw()});$('#filter').onchange=e=>{state.recipe.filter=e.target.value;draw()};$('#search').oninput=()=>{state.page=1;clearTimeout(state.searchTimer);state.searchTimer=setTimeout(load,250)};$('#closeEditor').onclick=()=>$('#editor').classList.add('hidden');$('#editor').onclick=e=>{if(e.target.id==='editor')$('#editor').classList.add('hidden')};$('#modeBtn').onclick=()=>{state.mode=state.mode==='operator'?'visitor':'operator';let b=$('#modeBtn');b.textContent=state.mode==='operator'?'牛马模式':'游客模式';b.className=`mode ${state.mode}`;$('#saveVariant').disabled=state.mode==='visitor';$('#exportVariant').disabled=state.mode==='visitor'};
$('#saveVariant').onclick=async()=>{try{let v=await api('/api/recipes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({asset_id:state.asset.id,recipe:{...state.recipe}})});state.asset.recipes.push(v);renderVariants();alert('Variant saved.')}catch(e){alert(e.message)}};
let wbLabel=document.querySelector('[data-key="adjustments.temperature"]')?.parentElement;if(wbLabel){wbLabel.insertAdjacentHTML('beforeend','<button id="autoWB" class="auto-wb" type="button">Auto WB</button>');$('#autoWB').onclick=autoWhiteBalance}
$('#exportVariant').onclick=async()=>{try{draw(true);let data=$('#canvas').toDataURL('image/jpeg',.92);draw(false);let r=await api('/api/export',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({data_url:data,filename:`${state.asset.name.replace(/\.[^.]+$/,'')}-edit.jpg`})});alert(`Exported to ${r.path}`)}catch(e){draw(false);alert(e.message)}};
function setTool(tool){state.tool=tool;$('#handTool').classList.toggle('active',tool==='hand');$('#zoomTool').classList.toggle('active',tool==='zoom');$('#canvas').style.cursor=tool==='hand'?'grab':'zoom-in'}
function setZoom(value){state.zoom=Math.max(.5,Math.min(5,value));draw()}
$('#handTool').onclick=()=>setTool('hand');$('#zoomTool').onclick=()=>setTool('zoom');$('#zoomIn').onclick=()=>setZoom(state.zoom+.25);$('#zoomOut').onclick=()=>setZoom(state.zoom-.25);$('#zoomReset').onclick=()=>{state.zoom=1;state.panX=0;state.panY=0;draw()};$('#canvas').onclick=e=>{if(state.tool==='zoom'){setZoom(state.zoom+(e.shiftKey?-.25:.25))}};$('#canvas').onpointerdown=e=>{if(state.tool!=='hand')return;state.drag={x:e.clientX,y:e.clientY,panX:state.panX,panY:state.panY};$('#canvas').setPointerCapture(e.pointerId);$('#canvas').style.cursor='grabbing'};$('#canvas').onpointermove=e=>{if(!state.drag)return;state.panX=state.drag.panX+e.clientX-state.drag.x;state.panY=state.drag.panY+e.clientY-state.drag.y;draw()};$('#canvas').onpointerup=e=>{state.drag=null;$('#canvas').style.cursor='grab'};setTool('hand');
loadFolders().then(load).catch(e=>{$('#status').textContent=e.message;$('#grid').innerHTML=`<div class="empty">${esc(e.message)}</div>`});
