(function(){
  const api=async(url,opts={})=>{opts.headers={...(opts.headers||{}),'X-App-Mode':'operator'};const response=await fetch(url,opts),data=await response.json();if(!response.ok)throw Error(data.error||response.statusText);return data};
  const page=type=>{
    document.querySelector('#standaloneJobPage')?.remove();
    document.querySelector('.layout')?.classList.add('hidden');
    document.querySelector('#jobsView')?.classList.add('hidden');
    const isStack=type==='stack_generation',title=isStack?'图片找朋友':'生成缩略图',description=isStack?'按相邻照片和 pHash 距离生成 photo stacks':'生成等比例缩小图，供图库浏览和后续特征任务使用';
    const host=document.createElement('section');host.id='standaloneJobPage';host.className='jobs-view';
    host.innerHTML=`<div class="jobs-head"><div><span class="eyebrow">ADVANCED JOB</span><h2>${title}</h2><div class="subtle">${description}</div></div><button id="standaloneNew" class="job-add-button" type="button" aria-label="新建任务" title="新建任务">+</button></div><div class="job-detail"><div id="standaloneJobList" class="standalone-job-list"></div></div>`;
    document.body.append(host);
    const list=host.querySelector('#standaloneJobList');let sequence=0;
    const runnerMarkup=key=>`<article class="job-run-card standalone-job-card" data-runner="${key}"><div class="standalone-fields"><label>处理范围<input data-field="folder" type="text" placeholder="例如：2022/2022_01"></label>${isStack?'<label>最大时间间隔（分钟）<input data-field="gap" type="number" min="0.1" step="0.1" value="15"></label><label>pHash Hamming distance<input data-field="distance" type="number" min="0" max="63" step="1" value="20"></label>':''}</div><div class="actions"><button data-action="start" class="primary" type="button">开始</button><button data-action="clean" class="clean-start" type="button">强行重开</button><button data-action="cancel" type="button" disabled>取消任务</button></div><div class="standalone-progress"><div class="progress-top"><span data-output="stage">READY</span><strong data-output="percent">0%</strong></div><div class="progress-track"><div data-output="fill"></div></div><div class="progress-meta"><span data-output="count">0 / 0</span><span data-output="errors">0 errors</span></div></div><p data-output="status" class="subtle">${isStack?'默认复用已有 pHash；点击“强行重开”后全部重新计算。':'默认跳过已有 thumbnail；点击“强行重开”后会全部重建。'}</p></article>`;
    const setupRunner=(runner,existing=null)=>{
      const folder=runner.querySelector('[data-field="folder"]');
      const start=runner.querySelector('[data-action="start"]'),cancel=runner.querySelector('[data-action="cancel"]'),clean=runner.querySelector('[data-action="clean"]'),stage=runner.querySelector('[data-output="stage"]'),percent=runner.querySelector('[data-output="percent"]'),fill=runner.querySelector('[data-output="fill"]'),count=runner.querySelector('[data-output="count"]'),errors=runner.querySelector('[data-output="errors"]'),status=runner.querySelector('[data-output="status"]');
      let jobId=existing?.id||null,timer=null;
      fetch('/api/folders',{headers:{'X-App-Mode':'operator'}}).then(response=>response.json()).then(data=>setupFolderAutocomplete(folder,data.folders||[])).catch(()=>{});
      if(existing){folder.value=existing.scope.folder||'';if(isStack){runner.querySelector('[data-field="gap"]').value=existing.scope.max_gap_minutes??15;runner.querySelector('[data-field="distance"]').value=existing.scope.max_phash_distance??20}if(existing.scope.clean_start&&clean)clean.classList.add('active');start.disabled=true;cancel.disabled=false;stage.textContent=String(existing.state).toUpperCase()}
      if(clean)clean.onclick=()=>{clean.classList.toggle('active');status.textContent=clean.classList.contains('active')?'本次将强制重建全部 thumbnail。':'默认跳过已有 thumbnail。'};
      const update=async()=>{if(!jobId)return;try{const job=await api(`/api/jobs/${jobId}`),detail=job.progress_detail||{},value=Math.max(0,Math.min(100,Number(job.progress)||0)),processed=detail.images_scanned??detail.stage_processed??0,total=detail.images_total??detail.stage_total??0;stage.textContent=String(detail.stage||job.state).toUpperCase();percent.textContent=`${value}%`;fill.style.width=`${value}%`;count.textContent=`${processed} / ${total}`;errors.textContent=`${detail.errors||0} errors`;status.textContent=isStack?`${detail.stacks||0} stacks · computed ${detail.hashes_computed||0} · skipped ${detail.hashes_skipped||0} · pHash ≤ ${detail.max_phash_distance??job.scope.max_phash_distance??'未知'}`:`${detail.thumbnails_created||0} created · ${detail.thumbnails_skipped||0} skipped`;if(job.state==='completed'||job.state==='failed'||job.state==='cancelled'){start.disabled=false;cancel.disabled=true;jobId=null;if(timer)clearTimeout(timer);if(job.error)status.textContent+=` · ${job.error}`;return}timer=setTimeout(update,700)}catch(error){errors.textContent=error.message;start.disabled=false;cancel.disabled=true;jobId=null}};
      start.onclick=async()=>{const scope={folder:folder.value.trim(),clean_start:clean.classList.contains('active')};if(!scope.folder){status.textContent='请填写处理范围';return}if(isStack){scope.max_gap_minutes=Number(runner.querySelector('[data-field="gap"]').value);scope.max_phash_distance=Number(runner.querySelector('[data-field="distance"]').value)}try{const job=await api('/api/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,scope})});jobId=job.id;start.disabled=true;cancel.disabled=false;stage.textContent='QUEUED';percent.textContent='0%';fill.style.width='0%';count.textContent='0 / 0';errors.textContent='0 errors';status.textContent='任务已排队';update()}catch(error){status.textContent=error.message}};
      cancel.onclick=async()=>{if(!jobId)return;try{await api(`/api/jobs/${jobId}/cancel`,{method:'POST'});status.textContent='cancelled';start.disabled=false;cancel.disabled=true;jobId=null;if(timer)clearTimeout(timer)}catch(error){status.textContent=error.message}};
      if(existing&&(existing.state==='queued'||existing.state==='running'))update();
    };
    const addRunner=(existing=null,before=false)=>{const key=`runner-${++sequence}`;list.insertAdjacentHTML(before?'afterbegin':'beforeend',runnerMarkup(key));const runner=list.querySelector(`[data-runner="${key}"]`);setupRunner(runner,existing);if(!existing)runner.querySelector('[data-field="folder"]').focus();return runner};
    host.querySelector('#standaloneNew').onclick=()=>addRunner(null,true);
    api('/api/jobs').then(data=>{const active=data.jobs.filter(job=>job.type===type&&(job.state==='queued'||job.state==='running'));if(active.length)active.reverse().forEach(job=>addRunner(job));else addRunner()}).catch(()=>addRunner());
  };
  window.JobPages={mount:page};
  const thumbnailButton=document.querySelector('#runThumbnailJob'),stackingButton=document.querySelector('#runStackJob');
  if(thumbnailButton)thumbnailButton.onclick=()=>{window.location.href='/jobs/thumbnail-generation'};
  if(stackingButton)stackingButton.onclick=()=>{window.location.href='/jobs/stacking'};
})();
